### ISSUE TITLE
Doesn't run as appimage on Mint

### ISSUE THREAD

**Issue by eugenialoli** [mfat/systemd-pilot#1]
Thank you for this utility, much needed. It doesn't run on my Mint 22 though:

eugenia@MacBookAir-2015:~/Downloads$ ./SystemD_Pilot-1.0.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_System5raGOs/usr/bin/systemd-pilot", line 4, in <module>
    gi.require_version('Adw', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available

**Comment by eugenialoli** [comment]
Yes, these are dev packages that don't come installed by default, these need to be part of the appimage, that's the point of the appimage/flatpaks/snaps. For libraries that are common, no need to bundle them, but for dev packages , these aren't installed by default on debian-based systems.

So, anyway, I installed these libraries, and now the app loads, but it still has lots of warnings:


./SystemD_Pilot-1.0.AppImage 

(python3:22730): Gtk-WARNING **: 15:38:29.540: Tried to remove non-child 0x23545a90
Error executing command as another user: Request dismissed
Traceback (most recent call last):
  File "/tmp/.mount_SystemfpJofa/usr/bin/systemd-pilot", line 349, in run_systemctl_command
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkexec', 'systemctl', 'start', 'casper-md5check.service']' returned non-zero exit status 126.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_SystemfpJofa/usr/bin/systemd-pilot", line 367, in on_start_service
    self.run_systemctl_command("start", service_name)
  File "/tmp/.mount_SystemfpJofa/usr/bin/systemd-pilot", line 364, in run_systemctl_command
    self.show_error_dialog(f"Failed to {command} service: {e}")
  File "/tmp/.mount_SystemfpJofa/usr/bin/systemd-pilot", line 456, in show_error_dialog
    dialog = Adw.MessageDialog.new(
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Adw.MessageDialog.new() got an unexpected keyword argument 'transient_for'

**Comment by mfat** [comment]
Thanks. I'll look 8nto this. Did you also try the deb package? @eugenialoli

**Comment by eugenialoli** [comment]
Thanks, appreciated! No, just used the appimage.

**Comment by mfat** [comment]
@eugenialoli Can you please try this appimage and report back?
https://github.com/mfat/systemd-pilot/releases/download/v1.1/SystemD_Pilot_1.1-x86_64.AppImage
And please try after uninstalling the dev packages you installed before too. Thanks.

**Comment by eugenialoli** [comment]
Yes, this works perfectly, thank you! I did remove the libs before trying.

**Comment by mfat** [comment]
Many thanks for confirming. Version 1.2 is out. Please try the flatpak or wait for appimage/deb.

**Comment by eugenialoli** [comment]
Version 1.2 does NOT work again (while v1.1 did work!).

`eugenia@MacBookAir-2015:~/Downloads$ ./systemdPilot-v1.2.AppImage 

** (process:38471): WARNING **: 14:57:08.603: Failed to load shared library 'libgio-2.0.so.0' referenced by the typelib: /lib/x86_64-linux-gnu/libmount.so.1: version `MOUNT_2_40' not found (required by /tmp/.mount_system0QiAdV/usr/lib/libgio-2.0.so.0)
Traceback (most recent call last):
  File "/tmp/.mount_system0QiAdV/usr/lib/systemd_pilot/main.py", line 5, in <module>
    from gi.repository import Gtk, Adw, GLib, Gio, Gdk, Pango
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 146, in create_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 146, in create_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 146, in create_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 146, in create_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 146, in create_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 147, in create_module
    dynamic_module = load_overrides(introspection_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 112, in load_overrides
    override_mod = importlib.import_module(override_package_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 37, in <module>
    class Application(Gio.Application):
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 177, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 99, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 31, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 217, in __getattr__
    wrapper = metaclass(name, bases, dict_)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/types.py", line 247, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
`

**Comment by mfat** [comment]
@eugenialoli This should work: https://github.com/mfat/systemd-pilot/releases/download/v1.2/systemdPilot-v1.2.AppImage

**Comment by eugenialoli** [comment]
Yes, this one works, thx.

**Comment by mfat** [comment]
@eugenialoli Great. Really appreciate your help. Updated the release with this file.
